# Build Jekyll configuration
# These settings override _config.yml on `grunt build`

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

# Include Disqus comments when build
comments: true
dq: sungsit

ga:
  status: true
  id: UA-39671868-1
